CREATE TABLE [contract].[contract_mutation] (
    [contract_mutation_id]                     INT              IDENTITY (1, 1) NOT NULL,
    [contract_id]                              INT              NOT NULL,
    [contract_base_id]                         INT              NOT NULL,
    [contract_type_id]                         INT              NOT NULL,
    [organizational_unit_id]                   INT              NOT NULL,
    [organizational_unit_department_id]        INT              NULL,
    [cao_id]                                   INT              NOT NULL,
    [cao_leave_regulation_id]                  INT              NULL,
    [contract_mutation_start_date]             DATE             NOT NULL,
    [contract_mutation_end_date]               DATE             NULL,
    [contract_mutation_min_hours]              DECIMAL (36, 18) NOT NULL,
    [contract_mutation_max_hours]              DECIMAL (36, 18) NOT NULL,
    [contract_mutation_extra]                  DECIMAL (36, 18) NULL,
    [contract_mutation_wage_deduction]         BIT              NULL,
    [contract_mutation_has_buffer_hours]       BIT              NULL,
    [contract_mutation_has_compensation_hours] BIT              NULL,
    [contract_probation_end_date]              DATE             NULL,
    [internal_contract_identifier]             NVARCHAR (MAX)   NULL,
    [contract_employment_number]               NVARCHAR (MAX)   NULL,
    [create_date]                              DATETIME         NULL,
    [modify_date]                              DATETIME         NULL,
    [delete_date]                              DATETIME         NULL,
    CONSTRAINT [PK_contract_mutation] PRIMARY KEY CLUSTERED ([contract_mutation_id] ASC) WITH (FILLFACTOR = 90),
    CONSTRAINT [FK_contract_mutation_cao] FOREIGN KEY ([cao_id]) REFERENCES [contract].[cao] ([cao_id]),
    CONSTRAINT [FK_contract_mutation_cao1] FOREIGN KEY ([cao_leave_regulation_id]) REFERENCES [contract].[cao] ([cao_id]),
    CONSTRAINT [FK_contract_mutation_contract] FOREIGN KEY ([contract_id]) REFERENCES [contract].[contract] ([contract_id]),
    CONSTRAINT [FK_contract_mutation_contract_base] FOREIGN KEY ([contract_base_id]) REFERENCES [contract].[contract_base] ([contract_base_id]),
    CONSTRAINT [FK_contract_mutation_contract_type] FOREIGN KEY ([contract_type_id]) REFERENCES [contract].[contract_type] ([contract_type_id]),
    CONSTRAINT [FK_contract_mutation_organizational_unit] FOREIGN KEY ([organizational_unit_id]) REFERENCES [organisation].[organizational_unit] ([organizational_unit_id]),
    CONSTRAINT [FK_contract_mutation_organizational_unit1] FOREIGN KEY ([organizational_unit_department_id]) REFERENCES [organisation].[organizational_unit] ([organizational_unit_id])
);

