//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievements_Manager
    {
        public int ManagerManager_ID { get; set; }
        public int AchievementsAchievements_ID { get; set; }
        public Nullable<int> Voortgang { get; set; }
        public Nullable<bool> Behaald { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
