//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public Achievement()
        {
            this.Achievements_Manager = new HashSet<Achievements_Manager>();
        }
    
        public int Achievement_ID { get; set; }
        public string Naam { get; set; }
        public byte[] Logo { get; set; }
        public string Instructie { get; set; }
        public Nullable<int> Beloning { get; set; }
    
        public virtual ICollection<Achievements_Manager> Achievements_Manager { get; set; }
    }
}
