//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competitie_Club
    {
        public int Competitie_Club_ID { get; set; }
        public int ClubClub_ID { get; set; }
        public int CompetitieCompetitie_ID { get; set; }
        public Nullable<int> Positie { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Competitie Competitie { get; set; }
    }
}
