//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public Land()
        {
            this.Clubs = new HashSet<Club>();
            this.Competities = new HashSet<Competitie>();
            this.Managers = new HashSet<Manager>();
        }
    
        public int Land_Code { get; set; }
        public string Naam { get; set; }
        public string Continent { get; set; }
        public byte[] Vlag { get; set; }
    
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Competitie> Competities { get; set; }
        public virtual ICollection<Manager> Managers { get; set; }
    }
}
