//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager_Competitie
    {
        public int Manager_Competitie_ID { get; set; }
        public int CompetitieCompetitie_ID { get; set; }
        public int ClubClub_ID { get; set; }
        public Nullable<int> ManagerPunten { get; set; }
    }
}
