//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OSMEntities3 : DbContext
    {
        public OSMEntities3()
            : base("name=OSMEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Achievements_Manager> Achievements_Manager { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Competitie> Competities { get; set; }
        public virtual DbSet<Competitie_Club> Competitie_Club { get; set; }
        public virtual DbSet<Land> Lands { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Manager_Competitie> Manager_Competitie { get; set; }
        public virtual DbSet<Wedstrijd> Wedstrijds { get; set; }
    }
}
