CREATE TABLE [childcontract].[child_contract] (
    [child_contract_id]              INT             IDENTITY (1, 1) NOT NULL,
    [contact_id]                     INT             NOT NULL,
    [organizational_unit_id]         INT             NOT NULL,
    [child_contract_type_id]         INT             NOT NULL,
    [organizational_unit_subtype_id] INT             NULL,
    [prospect_response_id]           INT             NULL,
    [prospect_demand_id]             INT             NULL,
    [prospect_status_id]             INT             NULL,
    [child_contract_overview_id]     INT             NULL,
    [child_contract_subtype_id]      INT             NULL,
    [child_contract_minimal_hours]   DECIMAL (10, 2) NULL,
    [child_contract_maximal_hours]   DECIMAL (10, 2) NULL,
    [child_contract_margin_days]     INT             NULL,
    [child_contract_start_date]      DATE            NULL,
    [child_contract_end_date]        DATE            NULL,
    [child_contract_identifier]      NVARCHAR (100)  NULL,
    [child_contract_sequence_number] INT             NULL,
    [child_contract_comment]         NVARCHAR (MAX)  NULL,
    [create_date]                    DATETIME        NULL,
    [modify_date]                    DATETIME        NULL,
    [delete_date]                    DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([child_contract_id] ASC),
    CONSTRAINT [FK_child_contract_child_contract_overview] FOREIGN KEY ([child_contract_overview_id]) REFERENCES [childcontract].[child_contract_overview] ([child_contract_overview_id]),
    CONSTRAINT [FK_child_contract_child_contract_subtype] FOREIGN KEY ([child_contract_subtype_id]) REFERENCES [childcontract].[child_contract_subtype] ([child_contract_subtype_id]),
    CONSTRAINT [FK_child_contract_child_contract_type] FOREIGN KEY ([child_contract_type_id]) REFERENCES [childcontract].[child_contract_type] ([child_contract_type_id]),
    CONSTRAINT [FK_child_contract_contact] FOREIGN KEY ([contact_id]) REFERENCES [contact].[contact] ([contact_id]),
    CONSTRAINT [FK_child_contract_organizational_unit] FOREIGN KEY ([organizational_unit_id]) REFERENCES [organisation].[organizational_unit] ([organizational_unit_id]),
    CONSTRAINT [FK_child_contract_organizational_unit_subtype] FOREIGN KEY ([organizational_unit_subtype_id]) REFERENCES [organisation].[organizational_unit_subtype] ([organizational_unit_subtype_id]),
    CONSTRAINT [FK_child_contract_prospect_demand] FOREIGN KEY ([prospect_demand_id]) REFERENCES [childcontract].[prospect_demand] ([prospect_demand_id]),
    CONSTRAINT [FK_child_contract_prospect_response] FOREIGN KEY ([prospect_response_id]) REFERENCES [childcontract].[prospect_response] ([prospect_response_id]),
    CONSTRAINT [FK_child_contract_prospect_status] FOREIGN KEY ([prospect_status_id]) REFERENCES [childcontract].[prospect_status] ([prospect_status_id])
);

